### PR TITLE
fix: actor item corner radius

### LINKED ISSUE #411: 45- the actor image is not supported in the RTL screen layout

### PR DESCRIPTION
**Pull request by aabukmail**
# What does this PR do?
The `ActorItem` composable now correctly applies rounded corners based on the layout direction (RTL/LTR). Previously, the `bottomStart` and `bottomEnd` corners were swapped in RTL layouts.

## Type of Change
- [x] 🐛 Bug fix
- [x] 🔧 Refactoring
- [x] 🎨 UI changes

## Changes Made
- [x] Compose UI

## Screenshots
image

### CODE REVIEW

**Review by Mostafa-alsaygh — DISMISSED** [review]

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

File: designSystem/src/main/java/com/london/designsystem/component/ActorItem.kt [hunk 1]
```diff
@@ -57,8 +57,8 @@ private fun ActorImage(imageRes: Any) {
     val imageShape = RoundedCornerShape(
         topStart = 12.dp,
         topEnd = 12.dp,
-        bottomStart = if (isRtl) 0.dp else 12.dp,
-        bottomEnd = if (isRtl) 12.dp else 0.dp
+        bottomStart = if (isRtl) 12.dp else 12.dp,
+        bottomEnd = if (isRtl) 0.dp else 0.dp
```
Comment (BassantM) [inline designSystem/src/main/java/com/london/designsystem/component/ActorItem.kt]: kindly make it 
bottomStart = 12.dp,
        bottomEnd = 0.dp

**Review by BassantM — APPROVED** [review]

**Review by AsmaaKhaledGomaa — APPROVED** [review]
