### PR TITLE
fix: refactor top movies picks

### LINKED ISSUE #614: refactor top movies picks

### PR DESCRIPTION
**Pull request by Abdulrahman-Ragab-01**
# What does this PR do?

refactor top movies picks presentation module

## Type of Change
- [x] 🔧 Refactoring

## Testing
- [x] Unit tests added/updated
- [x] UI tests added/updated

## Checklist
- [x] Tests pass

### CODE REVIEW

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt [hunk 1]
```diff
@@ -1,8 +1,8 @@
 package com.london.presentation.feature.details.actor.info.topmoviespicks
 
 interface TopMoviesPicksContract {
-    fun onSaveMovie(movieId: Int)
-    fun onMovieClicked(movieId: Int)
-    fun onBack()
     fun onRetry()
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt]: rename all functions to follow the same suffix (click)

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt [hunk 2]
```diff
@@ -2,5 +2,5 @@ package com.london.presentation.feature.details.actor.info.topmoviespicks
 
 sealed interface TopMoviesPicksEffect {
     data object NavigateBack : TopMoviesPicksEffect
-    data class NavigationToMovieDetails(val movieId: Int) : TopMoviesPicksEffect
-}
\ No newline at end of file
+    data class NavigateToMovieDetails(val movieId: Int) : TopMoviesPicksEffect
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt]: i think class should be noun not verb, yeah?

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt [hunk 3]
```diff
@@ -2,5 +2,5 @@ package com.london.presentation.feature.details.actor.info.topmoviespicks
 
 sealed interface TopMoviesPicksEffect {
     data object NavigateBack : TopMoviesPicksEffect
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt]: same here

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt [hunk 4]
```diff
@@ -10,13 +10,13 @@ import javax.inject.Inject
...
+    private val getActorMoviePicksById: GetActorMoviePicksByIdUseCase,
 ) : BaseViewModel<TopMoviesPicksUiState, TopMoviesPicksEffect>(TopMoviesPicksUiState()),
     TopMoviesPicksContract {
 
     private val args = savedStateHandle.getArgs<Screen.ActorTopMoviesPicksDetails>()
-    val actorId = args?.actorId ?: 0
+    private val actorId = args?.actorId ?: 0
 
     init {
         if (actorId != 0) {
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: you don't need this line because in the tryToExecute function you've implemented checkSuccess = { actorId != 0 }, so the call will not happen if the id is equal to zero

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 5]
```diff
@@ -0,0 +1,235 @@
...
+import org.junit.Test
+
+@OptIn(ExperimentalCoroutinesApi::class)
+class TopMoviesPicksViewModelTest {
+
+    private lateinit var viewModel: TopMoviesPicksViewModel
+    private lateinit var getActorMoviePicksById: GetActorMoviePicksByIdUseCase
+    private lateinit var savedStateHandle: SavedStateHandle
+    private val testScheduler = TestCoroutineScheduler()
+    private val testDispatcher = UnconfinedTestDispatcher(testScheduler)
```
Comment (ahmeddsamii) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: you can replace this to StandardTestDispatcher

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 6]
```diff
@@ -0,0 +1,235 @@
...
+        val actorId = 123
+        val args = Screen.ActorTopMoviesPicksDetails(actorId)
+        every { savedStateHandle.getArgs<Screen.ActorTopMoviesPicksDetails>() } returns args
+        coEvery { getActorMoviePicksById.invoke(actorId) } coAnswers {
+            delay(100)
+            mockCastDetails
+        }
+
+        // When
+        viewModel = TopMoviesPicksViewModel(savedStateHandle, getActorMoviePicksById)
```
Comment (ahmeddsamii) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: where is then? i mean you need to make assertion here

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 7]
```diff
@@ -0,0 +1,235 @@
...
+
+        // Then
+        coVerify(exactly = 0) { getActorMoviePicksById.invoke(any()) }
+        assertThat(viewModel.state.value.id).isEqualTo(0)
+        assertThat(viewModel.state.value.isLoading).isFalse()
+    }
+
+    @Test
+    fun `when checkSuccess returns false should not execute use case`() = runTest {
```
Comment (ahmeddsamii) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: i think this test case and `when actor ID is zero should not execute use case` are the same

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt (hunk 1 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt]: Retry is not clickable

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt (hunk 3 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt]: Same what?

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt (hunk 2 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt]: Any suggestions?

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt [hunk 8]
```diff
@@ -10,57 +10,42 @@ import javax.inject.Inject
...
-                        movieDetails = actorMovieDetails,
-                        isSaved = isSaved,
-                        backdropPath = backdropPath,
-                    )
-                }
-            },
-            onError = { errorState ->
-                updateState { copy(errorState = errorState) }
-            },
+            onSuccess = { actorMovieDetails -> updateState { copy(actorMovieDetails = actorMovieDetails) } },
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: Please separate this function from the others to improve readability and make it easier to test.

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+        savedStateHandle = mockk()
+    }
+
+    @After
+    fun tearDown() {
+        Dispatchers.resetMain()
+    }
+
+    @Test
+    fun `when onSaveClick called should toggle saved state`() = runTest {
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: Please rename the test function to
function name should return ... when onSaveClick ...

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt [hunk 10]
```diff
@@ -15,60 +14,58 @@ import com.london.presentation.utils.Listen
 
 @Composable
 fun TopMoviesPicksScreen(
-    onNavigateMovie: (Int) -> Unit,
     onNavigateBack: () -> Unit,
+    onNavigateMovie: (Int) -> Unit,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt]: i think on Navigate to Movie details

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt [hunk 11]
```diff
@@ -15,60 +14,58 @@ import com.london.presentation.utils.Listen
...
         isLoading = state.isLoading,
         isError = state.errorState is ErrorState.NoInternet,
-        onRetry = contract::onRetry,
+        onRetry = contract::onRetryClick,
     ) {
         MediaLazyGrid(
             title = stringResource(R.string.top_movies_picks),
-            items = state.movieDetails.cast,
-            onBack = contract::onBack,
+            items = state.actorMovieDetails.cast,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt]: is state.actorMovieDetails.cast movies not cast

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt [hunk 12]
```diff
@@ -4,10 +4,8 @@ import com.london.domain.entity.actordetails.cast.CastDetails
...
 data class TopMoviesPicksUiState(
-    val movieDetails: CastDetails = CastDetails(),
-    val errorState: ErrorState? = null,
-    val isLoading: Boolean = false,
     val isSaved: Boolean = false,
-    val backdropPath: String = "",
-    val id: Int = 0,
+    val isLoading: Boolean = false,
+    val errorState: ErrorState? = null,
+    val actorMovieDetails: CastDetails = CastDetails(),
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt]: i think this screen don't need this CastDetails it has movies true ?

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt [hunk 13]
```diff
@@ -4,10 +4,8 @@ import com.london.domain.entity.actordetails.cast.CastDetails
 import com.london.presentation.shared.base.ErrorState
 
 data class TopMoviesPicksUiState(
-    val movieDetails: CastDetails = CastDetails(),
-    val errorState: ErrorState? = null,
-    val isLoading: Boolean = false,
     val isSaved: Boolean = false,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt]: is saved for what

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt [hunk 14]
```diff
@@ -1,8 +1,8 @@
...
 interface TopMoviesPicksContract {
-    fun onSaveMovie(movieId: Int)
-    fun onMovieClicked(movieId: Int)
-    fun onBack()
-    fun onRetry()
-}
\ No newline at end of file
+    fun onBackClick()
+    fun onRetryClick()
+    fun onSaveClick(movieId: Int)
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksContract.kt]: i think onSaveMovieClick

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt [hunk 15]
```diff
@@ -10,57 +10,42 @@ import javax.inject.Inject
...
 
-    override fun onRetry(){
+    override fun onRetryClick() {
         updateState { copy(errorState = null) }
         getActorMoviePicksData()
     }
 
-    override fun onSaveMovie(movieId: Int) {
-        updateState { copy(isSaved = isSaved) }
+    override fun onSaveClick(movieId: Int) {
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: this method effect on all screen all movies in screen !!

Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: يعني ايه!!

Comment (marwanqashwa) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: i mean this method not implemented yet , this logic is wrong is saved in ui state

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt [hunk 16]
```diff
@@ -1,6 +1,6 @@
 package com.london.presentation.feature.details.actor.info.topmoviespicks
 
 sealed interface TopMoviesPicksEffect {
-    data object NavigateBack : TopMoviesPicksEffect
-    data class NavigationToMovieDetails(val movieId: Int) : TopMoviesPicksEffect
-}
\ No newline at end of file
+    data object BackNavigation : TopMoviesPicksEffect
```
Comment (Mostafa-alsaygh) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksEffect.kt:4]: bareq say "Navigation" name is not right
see in the recorded time 31:8

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt
Comment (Mostafa-alsaygh) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt:1]: make the override at first

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 17]
```diff
@@ -0,0 +1,92 @@
...
+
+@OptIn(ExperimentalCoroutinesApi::class)
+class TopMoviesPicksViewModelTest {
+
+    private lateinit var viewModel: TopMoviesPicksViewModel
+    private lateinit var getActorMoviePicksById: GetActorMoviePicksByIdUseCase
+    private lateinit var savedStateHandle: SavedStateHandle
+    private val testDispatcher = StandardTestDispatcher()
+
+    private val mockCastDetails = CastDetails(
```
Comment (Mostafa-alsaygh) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: make the fake data in the last of the file

**Review by Mostafa-alsaygh — DISMISSED** [review]

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt (hunk 11 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt]: Done, I solve it in actor details branch

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt (hunk 12 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt]: Done, I solve it in actor details brach

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt (hunk 15 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt]: done

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModel.kt:1]: done

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt (hunk 17 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: done

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt (hunk 11 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksScreen.kt]: check now, it is now solved in this branch

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt (hunk 12 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksUiState.kt]: check now it is now solved in current branch

**Review by Mostafa-alsaygh — DISMISSED** [review]

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

**Review by Mostafa-alsaygh — DISMISSED** [review]

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt [hunk 18]
```diff
@@ -0,0 +1,92 @@
...
+        viewModel = TopMoviesPicksViewModel(savedStateHandle, getActorMoviePicksById)
+
+        // Then
+        with(viewModel.state.value) {
+            assertThat(errorState).isNull()
+        }
+    }
+
+    @Test
+    fun `viewModel should implement all contract methods`() {
```
Comment (marwanqashwa) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: Where's the assertion in this method

**Review by marwanqashwa — COMMENTED** [review]
Good job

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt (hunk 18 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/test/java/com/london/presentation/feature/details/actor/info/topmoviespicks/TopMoviesPicksViewModelTest.kt]: check now

**Review by marwanqashwa — APPROVED** [review]

**Review by AsmaaKhaledGomaa — APPROVED** [review]
