### PR TITLE
fix getTvSessionVideo call api

### LINKED ISSUE #678: The top bar is behind the details data of any screen
https://github.com/user-attachments/assets/488b6766-bd15-4a39-9932-03b4bd60bc2f

### LINKED ISSUE #680: No bottom padding under the top bar in actor screen
Image

### PR DESCRIPTION
**Pull request by AbdelrhmanAyman20470**
# What does this PR do?

## Type of Change
- [x] 🐛 Bug fix

## Testing
- [x] Tested locally
- [x] Unit tests added/updated
- [x] UI tests added/updated

## Checklist
- [x] Code builds without warnings
- [x] Self-reviewed
- [x] Tests pass
- [x] Ready for review

### CODE REVIEW

File: data/src/main/java/com/london/data/remote/service/tvshow/TvShowApiService.kt [hunk 1]
```diff
@@ -59,9 +59,10 @@ interface TvShowApiService {
         @Path("episode_number") episodeNumber: Int,
     ): Response<VideoResponse>
 
-    @GET(ApiConstants.TV_SHOW_VIDEO_PATH)
-    suspend fun getTvShowVideos(
-        @Path("tv_id") tvShowId: Int,
+    @GET(ApiConstants.TV_SEASON_VIDEO_PATH)
+    suspend fun getTvSessionVideos(
+        @Path("series_id") tvShowId: Int,
```
Comment (yusufnasserdev) [inline data/src/main/java/com/london/data/remote/service/tvshow/TvShowApiService.kt]: Unify naming, this is `series_id`, the rest of the project is `tv_show_id`

File: data/src/main/java/com/london/data/remote/service/tvshow/TvShowApiService.kt [hunk 2]
```diff
@@ -59,9 +59,10 @@ interface TvShowApiService {
         @Path("episode_number") episodeNumber: Int,
     ): Response<VideoResponse>
 
-    @GET(ApiConstants.TV_SHOW_VIDEO_PATH)
-    suspend fun getTvShowVideos(
-        @Path("tv_id") tvShowId: Int,
+    @GET(ApiConstants.TV_SEASON_VIDEO_PATH)
+    suspend fun getTvSessionVideos(
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/remote/service/tvshow/TvShowApiService.kt]: rename this to tv season not session

File: data/src/main/java/com/london/data/remote/model/ApiConstants.kt [hunk 3]
```diff
@@ -30,7 +30,7 @@ object ApiConstants {
     const val TV_SHOW_EPISODE_BY_SEASON_PATH = "3/tv/{tv_id}/season/{season_number}"
     const val TV_SHOW_IMAGE = "3/tv/{tv_id}/images"
     const val EPISODE_DETAILS_PATH = "3/tv/{tv_id}/season/{season_number}/episode/{episode_number}"
-    const val TV_SHOW_VIDEO_PATH = "3/tv/{tv_id}/videos"
+    const val TV_SEASON_VIDEO_PATH = "3/tv/{series_id}/season/{season_number}/videos"
```
Comment (yusufnasserdev) [inline data/src/main/java/com/london/data/remote/model/ApiConstants.kt]: Unify naming, this is series_id, the rest of the project is tv_show_id

File: data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSource.kt [hunk 4]
```diff
@@ -24,7 +24,7 @@ interface TvShowRemoteDataSource {
     suspend fun deleteTvShowRating(tvShowId: Int, sessionId: String?): Result<RatingRemoteResponse>
     suspend fun getTopRatedTvShows(pageNumber: Int): Result<ApiResponse<TopRatedTvSeriesRemote>>
     suspend fun getTvShowDetailsById(id: Int): Result<TvShowDetailsRemoteResponse>
-    suspend fun getTvShowVideos(tvShowId: Int): Result<VideoResponse>
+    suspend fun getTvSessionVideo(tvShowId: Int, seasonNumber: Int): Result<VideoResponse>
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSource.kt]: rename this to tv season not session

File: data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSourceImpl.kt [hunk 5]
```diff
@@ -233,10 +233,17 @@ class TvShowRemoteDataSourceImpl @Inject constructor(
         mapper = { it }
     )
 
-    override suspend fun getTvShowVideos(tvShowId: Int): Result<VideoResponse> =
+    override suspend fun getTvSessionVideo(
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSourceImpl.kt]: rename this to tv season not session

File: data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSourceImpl.kt [hunk 6]
```diff
@@ -233,10 +233,17 @@ class TvShowRemoteDataSourceImpl @Inject constructor(
...
+        tvShowId: Int,
+        seasonNumber: Int
+    ): Result<VideoResponse> =
         callApiWithRetry(
-            apiCall = { tvShowApiService.getTvShowVideos(tvShowId = tvShowId) },
+            apiCall = {
+                tvShowApiService.getTvSessionVideos(
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/remote/source/tvshow/TvShowRemoteDataSourceImpl.kt]: rename this to tv season not session

File: data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt [hunk 7]
```diff
@@ -178,8 +178,8 @@ class TvShowRepositoryImpl @Inject constructor(
             episodeNumber = episodeNumber
         ).getOrThrow().videos?.map { it.youtubeKey.asYoutubeUrlOrEmpty() }.orEmpty()
 
-    override suspend fun getTvShowVideos(tvShowId: Int): List<String> =
-        tvShowRemoteDataSource.getTvShowVideos(tvShowId)
+    override suspend fun getTvSessionVideo(tvShowId: Int, seasonNumber: Int): List<String> =
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt]: rename this to tv season not session

File: data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt [hunk 8]
```diff
@@ -178,8 +178,8 @@ class TvShowRepositoryImpl @Inject constructor(
...
+        tvShowRemoteDataSource.getTvSessionVideo(tvShowId = tvShowId, seasonNumber = seasonNumber)
```
Comment (ahmeddsamii) [inline data/src/main/java/com/london/data/repository/tvshow/TvShowRepositoryImpl.kt]: rename this to tv season not session

File: data/src/test/java/com/london/data/repository/TvShowRepositoryImplTest.kt [hunk 9]
```diff
@@ -474,12 +474,18 @@ class TvShowRepositoryImplTest {
...
+                tvShowId = tvShowId,
+                seasonNumber = seasonNumber
+            )
+        } returns Result.success(
             fakeTvShowVideosResponse()
         )
 
         // When
-        val result: List<String> = repository.getTvShowVideos(tvShowId)
+        val result: List<String> = repository.getTvSessionVideo(tvShowId, seasonNumber)
```
Comment (yusufnasserdev) [inline data/src/test/java/com/london/data/repository/TvShowRepositoryImplTest.kt]: Video is non-descriptive, what type of video is it?

File: domain/src/main/java/com/london/domain/repository/TvShowRepository.kt [hunk 10]
```diff
@@ -54,7 +54,7 @@ interface TvShowRepository {
     ): TvShowEpisodeByIdEntity
 
     suspend fun getEpisodeVideos(seriesId: Int, seasonNumber: Int, episodeNumber: Int): List<String>
-    suspend fun getTvShowVideos(tvShowId: Int): List<String>
+    suspend fun getTvSessionVideo(tvShowId: Int, seasonNumber: Int): List<String>
```
Comment (ahmeddsamii) [inline domain/src/main/java/com/london/domain/repository/TvShowRepository.kt]: rename this to tv season not session

File: domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt [hunk 11]
```diff
@@ -54,8 +54,8 @@ class GetTvShowUseCase @Inject constructor(
         pageNumber = pageNumber
     )
 
-    suspend fun getTvShowVideo(tvShowId: Int): List<String> =
-        tvShowRepository.getTvShowVideos(tvShowId)
+    suspend fun getTvSessionVideo(tvShowId: Int, seasonNumber: Int): List<String> =
```
Comment (ahmeddsamii) [inline domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt]: rename this to tv season not session

File: domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt [hunk 12]
```diff
@@ -54,8 +54,8 @@ class GetTvShowUseCase @Inject constructor(
...
+        tvShowRepository.getTvSessionVideo(tvShowId = tvShowId, seasonNumber = seasonNumber)
```
Comment (ahmeddsamii) [inline domain/src/main/java/com/london/domain/usecase/details/tvshow/GetTvShowUseCase.kt]: rename this to tv season not session

File: presentation/src/main/java/com/london/presentation/feature/details/tvshow/info/TvShowDetailsViewModel.kt [hunk 13]
```diff
@@ -46,7 +45,7 @@ class TvShowDetailsViewModel @Inject constructor(
             block = {
                 val episodesBySeason =
                     getTvEpisodesUseCase.getTvShowEpisodesBySeason(tvShowId, seasonNumber)
-                val videoProvider = getTvShowUseCase.getTvShowVideo(tvShowId)
+                val videoProvider = getTvShowUseCase.getTvSessionVideo(tvShowId, seasonNumber)
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/tvshow/info/TvShowDetailsViewModel.kt]: rename this to tv season not session

**Review by yusufnasserdev — CHANGES_REQUESTED** [review]
Good work, I've left some notes.

**Review by yusufnasserdev — DISMISSED** [review]

**Review by yusufnasserdev — APPROVED** [review]

**Review by ahmeddsamii — APPROVED** [review]
