### PR TITLE
fix: issues from 43, 46, 47, 48, 49, 58

### LINKED ISSUE #386: 43- missing color gradient for the actor image in the details.
Image
Image

### LINKED ISSUE #387: 47- Gallery screen is not scrollable and doesn't care about the navigation bar padding.
Image

### LINKED ISSUE #388: 48- There is missing gradient in the movie/tv show image.
Image
Image

### LINKED ISSUE #389: 49- Device Rotation is locked :lock:

### LINKED ISSUE #390: 58. The radius for actors doesn't match the design radius
Image

### LINKED ISSUE #399: 46- Weird effect at the end of the blurred image.
Image

### PR DESCRIPTION
**Pull request by Abdulrahman-Ragab-01**
# What does this PR do?

check the issues description

## Type of Change
- [x] 🐛 Bug fix

### CODE REVIEW

**Review by aabukmail — DISMISSED** [review]

File: presentation/src/main/java/com/london/presentation/shared/CustomBackDropImagePager.kt [hunk 1]
```diff
@@ -109,6 +112,30 @@ fun CustomBackDropImagePager(
...
+            .clip(
+                shape = RoundedCornerShape(
+                    bottomStart = 12.dp,
+                    bottomEnd = 12.dp
+                )
+            )
+            .background(
+                brush = Brush.verticalGradient(
+                    colors = listOf(
+                        Color(0xff000000).copy(alpha = 0.5f),
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/main/java/com/london/presentation/shared/CustomBackDropImagePager.kt]: Please add to colors

File: designSystem/src/main/java/com/london/designsystem/component/button/ErrorImageBox.kt [hunk 2]
```diff
@@ -1,34 +1,22 @@
...
-            modifier = Modifier
-                .align(Alignment.Center),
-            contentScale = ContentScale.Crop,
-        )
-    }
+    Image(
+        painter = painterResource(
+            if (isDarkTheme) R.drawable.img_error_dark else R.drawable.img_error_light
+        ),
+        contentDescription = "Error Image",
```
Comment (AsmaaKhaledGomaa) [inline designSystem/src/main/java/com/london/designsystem/component/button/ErrorImageBox.kt]: Please add to string resources

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

**Review by aabukmail — APPROVED** [review]

**Review by Mostafa-alsaygh — APPROVED** [review]
