### PR TITLE
fix/login-bugs: update text field validation logic

### LINKED ISSUE #344: 8-there is width limit when the user inter his user name

### LINKED ISSUE #345: 12-As user I can’t understand what happened What is the meaning of status code?! True or false ?

### LINKED ISSUE #346: 11-there is a width limit for the username and password, it doesn't display the text.

### LINKED ISSUE #347: 10-there is no lower limit for the user to login.

### LINKED ISSUE #348: 9-the show and hide password icon has a different tint from the design

### PR DESCRIPTION
**Pull request by AbdelrhmanAyman20470**
# What does this PR do?

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🔧 Refactoring
- [ ] 🎨 UI changes

## Changes Made
- [ ] Compose UI
- [ ] Data
- [ ] Domain
- [ ] Koin DI
- [ ] Ktor API

## Testing
- [ ] Tested locally
- [ ] Unit tests added/updated
- [ ] UI tests added/updated

## Checklist
- [ ] Code builds without warnings
- [ ] Self-reviewed
- [ ] Tests pass
- [ ] Ready for review

### CODE REVIEW

**Review by ahmeddsamii — CHANGES_REQUESTED** [review]
Application is crashing, when i start run

image

**Comment by AbdelrhmanAyman20470** [comment]
> Application is crashing, when i start run
> 
> image

**Comment by AbdelrhmanAyman20470** [comment]
@ahmeddsamii i run it again and its didnt crash with me

**Review by ahmeddsamii — DISMISSED** [review]

File: designSystem/src/main/java/com/london/designsystem/component/OutlinedTextField.kt [hunk 1]
```diff
@@ -252,35 +263,23 @@ private fun AnimatedLeadingIcon(
...
     passwordVisibleIcon: Painter,
     passwordHiddenIcon: Painter,
     onToggle: () -> Unit
 ) {
-    if (isPasswordEmpty) {
+    IconButton(onClick = onToggle) {
         Icon(
-            painter = passwordHiddenIcon,
-            contentDescription = "Password field empty",
+            painter = if (passwordVisible) passwordVisibleIcon else passwordHiddenIcon,
```
Comment (AsmaaKhaledGomaa) [inline designSystem/src/main/java/com/london/designsystem/component/OutlinedTextField.kt]: If the password test field is empty, make the trailing icon non-clickable

File: presentation/src/main/java/com/london/presentation/feature/login/LoginViewModel.kt [hunk 2]
```diff
@@ -15,29 +15,27 @@ class LoginViewModel(
...
 
     override fun onPasswordChanged(password: TextFieldValue) {
-        val limited = limitTextFieldValue(password)
         updateState {
             copy(
-                password = limited,
-                isLoginEnabled = username.text.isNotEmpty() && limited.text.isNotEmpty(),
+                password = password,
+                isLoginEnabled = username.text.isNotEmpty()
+                        && password.text.isNotEmpty() && password.text.length >= 4,
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/main/java/com/london/presentation/feature/login/LoginViewModel.kt:32]: You can add the supportingText parameter to the OutlinedTextField to display the message: 'Password should be at least four characters

**Comment by AsmaaKhaledGomaa** [comment]
Screenshot (3)

add padding end

File: designSystem/src/main/java/com/london/designsystem/component/OutlinedTextField.kt [hunk 3]
```diff
@@ -60,7 +60,7 @@ fun OutlinedTextField(
     trailingIcon: @Composable (() -> Unit)? = null,
     supportingText: @Composable (() -> Unit)? = null,
     isError: Boolean = false,
-    contentPadding: PaddingValues = PaddingValues(horizontal = 12.dp),
+    contentPadding: PaddingValues = PaddingValues(start = 12.dp),
```
Comment (AsmaaKhaledGomaa) [inline designSystem/src/main/java/com/london/designsystem/component/OutlinedTextField.kt]: do not change horizontal 
Screenshot (3)

**Review by ahmeddsamii — DISMISSED** [review]

**Review by ahmeddsamii — APPROVED** [review]

**Review by AsmaaKhaledGomaa — APPROVED** [review]
