### PR TITLE
fix: Adjust spacing and item size in HomeScreen

### LINKED ISSUE #494: fix: 10- Adjust spacing and item size in HomeScreen

### PR DESCRIPTION
**Pull request by aabukmail**
# What does this PR do?
This pr makes the following changes to the HomeScreen:

- Decreases the minimum size for adaptive grid cells from 158dp to 120dp.
- Adjusts padding for the "upcoming" text and shimmer effect.
- Removes bottom padding from the GenreChipGroup.
- Removes top padding from the MovieItem.

## Type of Change
- [x] 🐛 Bug fix
- [x] 🔧 Refactoring
- [x] 🎨 UI changes

## Changes Made
- [x] Compose UI

## Screenshots
image

### CODE REVIEW

File: presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt [hunk 1]
```diff
@@ -310,12 +310,12 @@ private fun LazyGridScope.upComingSection(
                 text = stringResource(R.string.upcoming),
                 style = NovixTheme.typography.headline.small,
                 color = NovixTheme.colors.title,
-//                modifier = Modifier.padding(bottom = 4.dp)
+                modifier = Modifier
```
Comment (yusufnasserdev) [inline presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt]: This is not needed

File: presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt [hunk 2]
```diff
@@ -310,12 +310,12 @@ private fun LazyGridScope.upComingSection(
...
             )
         else
             Box(modifier = Modifier
                 .height(20.dp)
-                .padding(bottom = 4.dp)
+                .padding(bottom = 12.dp)
```
Comment (yusufnasserdev) [inline presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt]: This is for the shimmer effect, not related to the bug you're addressing.

Comment (aabukmail) [reply presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt]: I return for padding 4

File: presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt (hunk 1 above)
Comment (aabukmail) [reply presentation/src/main/java/com/london/presentation/feature/home/HomeScreen.kt]: I just delete the comment that I found and keep for modifier without any padding. I will delete it as you like.

**Review by yusufnasserdev — APPROVED** [review]

**Review by BassantM — APPROVED** [review]
