### PR TITLE
fix: enhance navigation in MovieDetailsScreen to go to any movie you click in

### LINKED ISSUE #213: movie details navigatio
When clicking on any cast, don't navigate to the actor details screen, same for movies in the similar section

### PR DESCRIPTION
**Pull request by BassantM**
# What does this PR do?
edit movie details ui state to enhance navigation in movie details screen, when u click on any movie you like,e u go to it directly, same for cast

### CODE REVIEW

File: presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsScreen.kt [hunk 1]
```diff
@@ -273,12 +279,14 @@ fun MovieDetailsContent(
...
-                        items(state.actors) { actor ->
+                        itemsIndexed(state.actors) {index, actor ->
                             ActorItem(
                                 actorName = actor.name,
                                 characterName = actor.characterName,
                                 imageRes = actor.avatarUrl,
-                                modifier = Modifier.defaultMinSize(minWidth = 296.dp)
+                                modifier = Modifier
+                                    .defaultMinSize(minWidth = 296.dp)
+                                    .clickable { onNavigateToActor(state.actors[index].actorId) }
```
Comment (Al-Taie) [inline presentation/src/main/java/com/london/presentation/screen/details/movieDetalis/MovieDetailsScreen.kt]:
```suggestion
                                    .clickable { onNavigateToActor(actor.actorId) }
```

**Review by marwanqashwa — DISMISSED** [review]

**Review by marwanqashwa — APPROVED** [review]

**Review by Mostafa-alsaygh — APPROVED** [review]
