### PR TITLE
fix: refactor top tv shows picks

### LINKED ISSUE #615: refactor top tv shows picks

### PR DESCRIPTION
**Pull request by Abdulrahman-Ragab-01**
# What does this PR do?

refactor top tv shows picks presentation

## Type of Change
- [x] 🔧 Refactoring

## Testing
- [x] Unit tests added/updated
- [x] UI tests added/updated

## Checklist
- [x] Tests pass

### CODE REVIEW

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksContract.kt [hunk 1]
```diff
@@ -1,8 +1,8 @@
 package com.london.presentation.feature.details.actor.info.toptvshowspicks
 
 interface TopTvShowsPicksContract {
-    fun onSaveTvShow(tvShowId: Int)
-    fun onTvShowClicked(tvShowId: Int)
-    fun onBack()
     fun onRetry()
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksContract.kt]: rename all function to have the same suffix

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksEffect.kt [hunk 2]
```diff
@@ -1,6 +1,6 @@
 package com.london.presentation.feature.details.actor.info.toptvshowspicks
 
 sealed interface TopTvShowsPicksEffect {
-    data class TvShowNavigation(val tvShowId: Int) : TopTvShowsPicksEffect
-    data object BackNavigation : TopTvShowsPicksEffect
-}
\ No newline at end of file
+    data object NavigateBack : TopTvShowsPicksEffect
+    data class NavigateToTvShowDetails(val tvShowId: Int) : TopTvShowsPicksEffect
```
Comment (ahmeddsamii) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksEffect.kt]: the class name should be noun not verb

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+        savedStateHandle = mockk()
+    }
+
+    @After
+    fun tearDown() {
+        Dispatchers.resetMain()
+    }
+
+    @Test
+    fun `when viewModel is initialized with null args should use default actorId`() = runTest {
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: Please rename the test function to
function name should return ... when onSaveClick ...

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt [hunk 4]
```diff
@@ -15,59 +14,57 @@ import com.london.presentation.utils.Listen
 
 @Composable
 fun TopTvShowsPicksScreen(
-    onNavigateTvShow: (Int) -> Unit,
     onNavigateBack: () -> Unit,
+    onNavigateTvShow: (Int) -> Unit,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: i think onNavigateTvShowDetails

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt [hunk 5]
```diff
@@ -15,59 +14,57 @@ import com.london.presentation.utils.Listen
...
         isLoading = state.isLoading,
         isError = state.errorState is ErrorState.NoInternet,
-        onRetry = contract::onRetry
+        onRetry = contract::onRetryClick
     ) {
         MediaLazyGrid(
             title = stringResource(R.string.top_tv_shows_picks),
-            items = state.tvShowDetails.cast,
-            onBack = contract::onBack,
+            items = state.actorTvShowDetails.cast,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: same i don't understand what is the cast i think screen have only tv shows

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksUiState.kt [hunk 6]
```diff
@@ -4,10 +4,8 @@ import com.london.domain.entity.actordetails.cast.CastDetails
 import com.london.presentation.shared.base.ErrorState
 
 data class TopTvShowsPicksUiState(
-    val tvShowDetails: CastDetails = CastDetails(),
-    val errorState: ErrorState? = null,
-    val isLoading: Boolean = false,
     val isSaved: Boolean = false,
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksUiState.kt]: this save for all tv shows in screen

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModel.kt [hunk 7]
```diff
@@ -25,39 +25,28 @@ class TopTvShowsPicksViewModel @Inject constructor(
...
     }
 
-    override fun onRetry(){
+    override fun onRetryClick() {
         updateState { copy(errorState = null) }
         getActorTvShowsPicksData()
     }
 
-    override fun onSaveTvShow(tvShowId: Int) {
+    override fun onSaveClick(tvShowId: Int) {
```
Comment (marwanqashwa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModel.kt]: i mean this

File: app/src/main/java/com/london/app/navigation/NovixApp.kt [hunk 8]
```diff
@@ -439,7 +439,7 @@ fun NavGraphBuilder.mainNavGraph(
         popExitTransition = { fadeOut(tween(500)) },
     ) {
         TopTvShowsPicksScreen(
```
Comment (Mostafa-alsaygh) [inline app/src/main/java/com/london/app/navigation/NovixApp.kt:441]: if this screen not used multiple times, move the navigation in to the screen

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksEffect.kt [hunk 9]
```diff
@@ -1,6 +1,6 @@
 package com.london.presentation.feature.details.actor.info.toptvshowspicks
 
 sealed interface TopTvShowsPicksEffect {
-    data class TvShowNavigation(val tvShowId: Int) : TopTvShowsPicksEffect
     data object BackNavigation : TopTvShowsPicksEffect
-}
\ No newline at end of file
+    data class TvShowDetailsNavigation(val tvShowId: Int) : TopTvShowsPicksEffect
```
Comment (Mostafa-alsaygh) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksEffect.kt:5]: the name is not right see the record in 31:00 min of bareq review

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+@OptIn(ExperimentalCoroutinesApi::class)
+class TopTvShowsPicksViewModelTest {
+
+    private lateinit var viewModel: TopTvShowsPicksViewModel
+    private lateinit var getActorTvShowPicksById: GetActorTvShowPicksByIdUseCase
+    private lateinit var savedStateHandle: SavedStateHandle
+    private val testScheduler = TestCoroutineScheduler()
+    private val testDispatcher = UnconfinedTestDispatcher(testScheduler)
+
+    private val mockCastDetails = CastDetails(
```
Comment (Mostafa-alsaygh) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: move the fake data in the last of file of in separate one

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+        val actorId = 123
+        val args = Screen.TopTvShowsPicksDetails(actorId)
+        every { savedStateHandle.getArgs<Screen.TopTvShowsPicksDetails>() } returns args
+        coEvery { getActorTvShowPicksById.invoke(actorId) } returns mockCastDetails
+
+        // When
+        viewModel = TopTvShowsPicksViewModel(savedStateHandle, getActorTvShowPicksById)
+
+        // Then
+        viewModel.onRetryClick()
```
Comment (Mostafa-alsaygh) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: thats not right see my PR 
u should Listen to the effect

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt [hunk 12]
```diff
@@ -15,59 +14,57 @@ import com.london.presentation.utils.Listen
...
 fun TopTvShowsPicksScreen(
-    onNavigateTvShow: (Int) -> Unit,
     onNavigateBack: () -> Unit,
+    onNavigateToTvShowDetails: (Int) -> Unit,
     viewModel: TopTvShowsPicksViewModel = hiltViewModel(),
 ) {
     val state by viewModel.state.collectAsStateWithLifecycle()
     val effect by viewModel.effect.collectAsState(initial = null)
 
     HandleTvShowsPicksEffects(
```
Comment (Mostafa-alsaygh) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: remove this fun and make directly

**Comment by Mostafa-alsaygh** [comment]
why the prefix name is fix and the name is refactor

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt [hunk 13]
```diff
@@ -0,0 +1,106 @@
...
+
+        // When
+        viewModel = TopTvShowsPicksViewModel(savedStateHandle, getActorTvShowPicksById)
+
+        // Then
+        coVerify(exactly = 1) { getActorTvShowPicksById.invoke(0) }
+    }
+
+    @Test
+    fun `should show loading state when data is being fetched`() = runTest {
```
Comment (harrytmthy) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: This test has no assertions. If it's meant to verify the "loading" state, consider comparing the state before and after the fetch.

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt [hunk 14]
```diff
@@ -0,0 +1,106 @@
...
+        // Given
+        val actorId = 123
+        val args = Screen.TopTvShowsPicksDetails(actorId)
+        every { savedStateHandle.getArgs<Screen.TopTvShowsPicksDetails>() } returns args
+        coEvery { getActorTvShowPicksById.invoke(actorId) } coAnswers {
+            delay(100)
```
Comment (harrytmthy) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: Rather than just using a real `delay(100)` in the stub, consider simulating the delay with virtual time using `advanceTimeBy(100)` or `advanceUntilIdle()`. This keeps the test fast and deterministic.

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt (hunk 10 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: done

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt (hunk 5 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: Done, I solve this in actor details branch

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt (hunk 14 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/test/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksViewModelTest.kt]: thank you for this info

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt (hunk 12 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: done

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt (hunk 5 above)
Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/toptvshowspicks/TopTvShowsPicksScreen.kt]: check now, its solved in this branch too

**Review by AsmaaKhaledGomaa — APPROVED** [review]

**Review by Mostafa-alsaygh — APPROVED** [review]
