### PR TITLE
fix: update save icon and outlined text field

### LINKED ISSUE #177: Issue 35 : Save button color is wrong in Light Mode
Image

### PR DESCRIPTION
**Pull request by karimdeabes**
Fixes layout and tint issues in the custom OutlinedTextField leading icon and the save icon.

## Screenshots
textIcon
Before
iconSizeBedfor
afterSave

## Type of Change
- [x] UI changes

## Changes Made
- [x] Compose UI

## Testing
- [x]Tested locally

 ## Checklist
 - [x] Tests pass

### CODE REVIEW

File: designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt [hunk 1]
```diff
@@ -45,7 +43,7 @@ fun SaveIcon(
         modifier = modifier
             .size(32.dp)
             .clip(RoundedCornerShape(8.dp))
-            .background(color = backgroundColor)
+            .background(color = NovixTheme.colors.iconBackground)
```
Comment (aabukmail) [inline designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt]: I put the background as a parameter that we can change, because we have a screen that has a different background.

**Review by Mostafa-alsaygh — DISMISSED** [review]

File: designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt [hunk 2]
```diff
@@ -32,7 +31,6 @@ fun SaveIcon(
     isSaved: Boolean,
     onSaveClick: () -> Unit,
     modifier: Modifier = Modifier,
-    backgroundColor: Color = NovixTheme.colors.iconBackground,
```
Comment (aabukmail) [inline designSystem/src/main/java/com/london/designsystem/component/SaveIcon.kt]: pls, return add this line

**Review by Mostafa-alsaygh — DISMISSED** [review]

**Review by AsmaaKhaledGomaa — DISMISSED** [review]

**Review by aabukmail — DISMISSED** [review]

**Review by marwanqashwa — DISMISSED** [review]

**Review by marwanqashwa — APPROVED** [review]

**Review by Abdulrahman-Ragab-01 — APPROVED** [review]

**Review by AsmaaKhaledGomaa — APPROVED** [review]
