### PR TITLE
fix: implement clickable navigation in episode details screen to navi…

### LINKED ISSUE #242: Tv show: Guests of honor not clickable

### PR DESCRIPTION
**Pull request by BassantM**
Gusts of Honos are clickable and navigate to the actor details screen right now

### CODE REVIEW

File: data/src/main/java/com/london/data/datasource/remote/details/actordetails/ActorDetailsRemoteDataSourceImpl.kt [hunk 1]
```diff
@@ -12,30 +12,30 @@ class ActorDetailsRemoteDataSourceImpl(
 ) : ActorDetailsRemoteDataSource {
 
     override suspend fun getActorDetailsById(
-        id: Int
+        actorId: Int
```
Comment (AsmaaKhaledGomaa) [inline data/src/main/java/com/london/data/datasource/remote/details/actordetails/ActorDetailsRemoteDataSourceImpl.kt]: The name of the function indicates that the id of the actor.

**Review by AsmaaKhaledGomaa — APPROVED** [review]

**Review by marwanqashwa — APPROVED** [review]
