### PR TITLE
fix: refactor actor gallery presentation

### LINKED ISSUE #616: refactor actor gallery

### PR DESCRIPTION
**Pull request by Abdulrahman-Ragab-01**
# What does this PR do?

refactor actor gallery presentation and add unit test

## Type of Change
- [x] 🔧 Refactoring

## Testing
- [x] Unit tests added/updated
- [x] UI tests added/updated

## Checklist
- [x] Tests pass
- [x] Ready for review

### CODE REVIEW

**Review by yusufnasserdev — COMMENTED** [review]
Bareq had asked us for an image-viewer like component when clicking on an image in the gallery, can we add this?

**Comment by Abdulrahman-Ragab-01** [comment]
> Bareq had asked us for an image-viewer like component when clicking on an image in the gallery, can we add this?

I think no need for that, cuz it is not in the design

File: presentation/src/test/java/com/london/presentation/feature/details/actor/info/gallery/ActorGalleryViewModelTest.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        savedStateHandle = mockk()
+    }
+
+    @After
+    fun tearDown() {
+        Dispatchers.resetMain()
+    }
+
+    @Test
+    fun `when onBackClick is called should emit NavigateBack effect`() = runTest {
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/test/java/com/london/presentation/feature/details/actor/info/gallery/ActorGalleryViewModelTest.kt]: Please rename the test function to
function name should return ... when onSaveClick ...

File: presentation/src/main/java/com/london/presentation/feature/details/actor/info/gallery/actorGalleryScreen.kt [hunk 2]
```diff
@@ -39,29 +39,29 @@ fun ActorGalleryScreen(
...
     }
 }
 
 @Composable
 private fun Content(
-    modifier: Modifier = Modifier,
+    uiState: ActorGalleryUiState,
     actorGalleryContract: ActorGalleryContract,
-    uiState: ActorGalleryUiState
+    modifier: Modifier = Modifier,
```
Comment (AsmaaKhaledGomaa) [inline presentation/src/main/java/com/london/presentation/feature/details/actor/info/gallery/actorGalleryScreen.kt]: Please remove the modifier from the content

Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/gallery/actorGalleryScreen.kt]: it is used in the column below, why you need to remove it?

Comment (Abdulrahman-Ragab-01) [reply presentation/src/main/java/com/london/presentation/feature/details/actor/info/gallery/actorGalleryScreen.kt]: I got you

**Review by BassantM — APPROVED** [review]
Great job👏

**Review by AsmaaKhaledGomaa — APPROVED** [review]
